site_name: CCPacks Documentation

nav:
    - Home: index.md
    - Universal Powers: universal_powers.md
    - Custom Content:
        - Blocks:
            - Generic: block/generic.md
            - Falling: block/falling.md
            - Stairs: block/stairs.md
            - Slab: block/slabs.md
            - Fence: block/fences.md
            - Fence Gate: block/fence_gates.md
            - Walls: block/walls.md
        - Items:
            - Armor: item/armor.md
            - Durable: item/durable.md
            - Food: item/food.md
            - Generic: item/generic.md
            - Shield: item/shield.md
            - Tools: item/tools.md
            - Trinket: item/trinket.md
            - Weapons: item/weapons.md
            - Discs: item/disc.md
            - Dyeable: item/dyeable.md
            - Pullback: item/pullback.md
        - Features:
            - Ore Generation: features/ore_gen.md
            - Tree Generation: features/tree_gen.md
        - Item Groups:
            - Generic: item_groups/generic.md
            - Tabbed: item_groups/tabbed.md
        - Status Effects:
            - Neutral: status_effect/neutral.md
            - Beneficial: status_effect/beneficial.md
            - Harmful: status_effect/harmful.md
        - Enchantments:
            - Generic: enchantment/generic.md
            - Curse: enchantment/curse.md
        - Portals:
            - Vertical: portal/vertical.md
            - Horizontal: portal/horizontal.md
        - Keybind: keybind.md
        - Projectile: projectile.md
        - Particle:
            - Generic: particle/generic.md
            - Emissive: particle/emissive.md
        - Sound Event: sound_event.md
    - Actions:
        - Entity Actions:
            - Change Stat: entity_actions/change_stat.md
            - Open Choice Screen: entity_actions/open_choice_screen.md
        - Block Actions:
            - Change Resource: block_actions/change_resource.md
            - Trigger Mechanic: block_actions/trigger_mechanic.md
    - Conditions:
        - Item Conditions:
            - Compare Durability: item_conditions/compare_durability.md
        - Entity Conditions:
            - Check Stat: entity_conditions/check_stat.md
            - Equipped Trinket: entity_conditions/equipped_trinket.md
            - Active Power Type: entity_conditions/active_power_type.md
        - Block Conditions:
            - Resource: block_conditions/resource.md
            - Exposed to Sun: block_conditions/exposed_to_sun.md
            - Block Pattern: block_conditions/block_pattern.md
    - Types:
        - Power Types: power_types.md
        - Mechanic Types: mechanic_types.md
        - Data Types: data_types.md
        - Choice JSON: choice_json.md
        - Layer JSON: layer_json.md
    - Apoli: https://ccpacks-docs.readthedocs.io/projects/apoli/en/latest/


theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

separator: '_'
plugins:
  - search
  - mermaid2:
      version: 8.6.4
      arguments:
          theme: 'neutral'

markdown_extensions:
    - admonition

extra_javascript:
    - https://unpkg.com/mermaid@8.7.0/dist/mermaid.min.js
