site_name: Origins Documentation
nav:
    - Home: index.md
    - Datapack Guides:
        - Defining an Origin: guides/data/define_origin.md
        - Defining a Power: guides/data/define_power.md
        - Origin conditions in layers: guides/data/origin_conditions_in_layers.md
    - Types:
        - Power Types: power_types.md
        - Data Types: data_types.md
        - Power JSON: power_json.md
        - Origin JSON: origin_json.md
        - Layer JSON: layer_json.md
    - Conditions:
        - Biome Conditions: biome_conditions.md
        - Block Conditions: block_conditions.md
        - Damage Conditions: damage_conditions.md
        - Entity Conditions: entity_conditions.md
        - Fluid Conditions: fluid_conditions.md
        - Item Conditions: item_conditions.md
        - Meta Conditions: meta_conditions.md
    - Actions:
        - Block Actions: block_actions.md
        - Entity Actions: entity_actions.md
        - Item Actions: item_actions.md
        - Meta Actions: meta_actions.md
    - Miscellaneous:
        - Commands: misc/commands.md
        - Keybindings: misc/keybindings.md
        - Origins: misc/origins.md
        - Positioned Item Stack Slots: misc/positioned_item_stack_slots.md
        - Powers: misc/origins_powers.md
        - Resource Bars: misc/resource_bars.md
        - Vanilla Damage Sources: misc/vanilla_damage_sources.md
       
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

separator: '_'
