site_name: CCPacks Documentation

nav:
    - Home: index.md
    - Pack Installation: pack_installation.md
    - Pack Structure: pack_structure.md
    - CCPacks:
        - Universal Powers: universal_powers.md
        - Custom Content:
            - Blocks: 
                - Generic: block/generic.md
                - Falling: block/falling.md
                - Stairs: block/stairs.md
                - Slab: block/slab.md
                - Fence: block/fence.md
                - Fence Gate: block/fence_gate.md
                - Walls: block/walls.md
                - Block Properties:
                    - Sounds: block/sounds.md
                    - Materials: block/materials.md
            - Items:
                - Armor: item/armor.md
                - Durable: item/durable.md
                - Food: item/food.md
                - Generic: item/generic.md
                - Shield: item/shield.md
                - Tools: item/tools.md
                - Trinket: item/trinket.md
                - Weapons: item/weapons.md
                - Discs: item/disc.md
            - Status Effects: 
                - Neutral: status_effect/neutral.md
                - Beneficial: status_effect/beneficial.md
                - Harmful: status_effect/harmful.md
            - Enchantments:
                - Generic: enchantment/generic.md
                - Curse: enchantment/curse.md
            - Portal: portal.md
            - Keybind: keybind.md
            - Particle:
                - Generic: particle/generic.md
                - Emissive: particle/emissive.md
            - Sound Event: sound_event.md
        - Actions:
            - Item Actions:
                - Change Name: item_actions/change_name.md
            - Entity Actions:
                - Open Decision Screen: entity_actions/open_decision_screen.md
                - Swing Hand: entity_actions/swing_hand.md
                - Set Stat: entity_actions/set_stat.md
                - Change Stat: entity_actions/change_stat.md
                - Block Raycast: entity_actions/raycast_block.md
        - Conditions:
            - Item Conditions:
                - Compare Durability: item_conditions/compare_durability.md
            - Entity Conditions:
                - Check Stat: entity_conditions/check_stat.md
        - Powers:
            - Stat Bar: powers/stat_bar.md
            - Action On Projectile Land: powers/action_on_projectile_land.md
    - Apoli:
        - Types:
            - Power Types: apoli/power_types.md
            - Data Types: apoli/data_types.md
            - Power JSON: apoli/power_json.md
        - Conditions:
            - Biome Conditions: apoli/biome_conditions.md
            - Block Conditions: apoli/block_conditions.md
            - Damage Conditions: apoli/damage_conditions.md
            - Entity Conditions: apoli/entity_conditions.md
            - Fluid Conditions: apoli/fluid_conditions.md
            - Item Conditions: apoli/item_conditions.md
            - Meta Conditions: apoli/meta_conditions.md
        - Actions:
            - Block Actions: apoli/block_actions.md
            - Entity Actions: apoli/entity_actions.md
            - Item Actions: apoli/item_actions.md
            - Meta Actions: apoli/meta_actions.md
        - Miscellaneous:
            - Vanilla Damage Sources: apoli/misc/vanilla_damage_sources.md

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

separator: '_'
plugins:
  - search
  - mermaid2:
      version: 8.6.4
      arguments:
          theme: 'neutral'
      
extra_javascript:
    - https://unpkg.com/mermaid@8.7.0/dist/mermaid.min.js