site_name: CCPacks Documentation
nav:
    - Home: index.md
    - Custom Content:
      - Blocks: blocks.md
      - Items:
        - Armor: item/armor.md
        - Durable Item: item/durable.md
        - Food: item/food.md
        - General: item/general.md
        - Tools: item/tools.md
        - Weapons: item/weapons.md
       
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

separator: '_'
