site_name: CCPacks Documentation

nav:
    - Home: index.md
    - Pack Structure: pack_structure.md
    - Custom Content:
        - Blocks: 
            - General: block/general.md
            - Falling Blocks: block/falling_block.md
            - Stairs: block/stairs.md
            - Slabs: block/slabs.md
        - Items:
            - Armor: item/armor.md
            - Durable Item: item/durable.md
            - Food: item/food.md
            - General: item/general.md
            - Trinket: item/trinket.md
            - Tools: item/tools.md
            - Weapons: item/weapons.md
        - Status Effects: effect.md
        - Enchantments: enchantment.md
        - Portal: portal.md
        - Keybind: keybind.md
        - Apoli:
            - Home: origins-docs/docs/index.md
            - Datapack Guides:
                - Defining an Origin: origins-docs/docs/guides/data/define_origin.md
                - Defining a Power: origins-docs/docs/guides/data/define_power.md
                - Origin conditions in layers: origins-docs/docs/guides/data/origin_conditions_in_layers.md
            - Add-on Guides:
                - Workspace Setup: origins-docs/docs/guides/addon/workspace_setup.md
                - Dependencies Explained: origins-docs/docs/guides/addon/dependencies.md
            - Types:
                - Power Types: origins-docs/docs/power_types.md
                - Data Types: origins-docs/docs/data_types.md
                - Power JSON: origins-docs/docs/power_json.md
                - Origin JSON: origins-docs/docs/origin_json.md
                - Layer JSON: origins-docs/docs/layer_json.md
            - Conditions:
                - Biome Conditions: origins-docs/docs/biome_conditions.md
                - Block Conditions: origins-docs/docs/block_conditions.md
                - Damage Conditions: origins-docs/docs/damage_conditions.md
                - Entity Conditions: origins-docs/docs/entity_conditions.md
                - Fluid Conditions: origins-docs/docs/fluid_conditions.md
                - Item Conditions: origins-docs/docs/item_conditions.md
                - Meta Conditions: origins-docs/docs/meta_conditions.md
            - Actions:
                - Block Actions: origins-docs/docs/block_actions.md
                - Entity Actions: origins-docs/docs/entity_actions.md
                - Item Actions: origins-docs/docs/item_actions.md
                - Meta Actions: origins-docs/docs/meta_actions.md
            - Miscellaneous:
                - Commands: origins-docs/docs/misc/commands.md
                - Keybindings: origins-docs/docs/misc/keybindings.md
                - Origins: origins-docs/docs/misc/origins.md
                - Positioned Item Stack Slots: origins-docs/docs/misc/positioned_item_stack_slots.md
                - Powers: origins-docs/docs/misc/origins_powers.md
                - Resource Bars: origins-docs/docs/misc/resource_bars.md
                - Vanilla Damage Sources: origins-docs/docs/misc/vanilla_damage_sources.md
    - Actions:
        - Item Actions:
            - Remove Durability: item_actions/remove_durability.md
            - Change Name: item_actions/change_name.md
        - Entity Actions:
            - Crafting GUI: entity_actions/crafting_gui.md
    - Conditions:
        - Item Conditions:
            - Compare Durability: item_conditions/compare_durability.md
            - Compare Amount: item_conditions/compare_amount.md

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

separator: '_'
plugins:
  - search
  - mermaid2:
      version: 8.6.4
      arguments:
          theme: 'neutral'
      
extra_javascript:
    - https://unpkg.com/mermaid@8.7.0/dist/mermaid.min.js